apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-secondary
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-controller
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: luneo-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secondary
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis_host
      remoteRef:
        key: /luneo/prod/backend-secondary
        property: redis_host
    - secretKey: openai_api_key
      remoteRef:
        key: /luneo/prod/backend-secondary
        property: openai_api_key

