apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-platform-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitops-platform-config
    app.kubernetes.io/managed-by: kustomize
data:
  registry: 123456789012.dkr.ecr.eu-west-1.amazonaws.com
  imageBackend: luneo-backend
  imageFrontend: luneo-frontend
  imageWorkerIa: luneo-worker-ia
  imageRender: luneo-render
  imageVersion: latest
  enableDemoMode: "false"
  enableRealtimeMonitoring: "true"

