apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-primary
  namespace: argocd
  labels:
    app.kubernetes.io/component: tracing
    luneo.io/region: eu-west-1
spec:
  project: default
  destination:
    name: arn:aws:eks:eu-west-1:123456789012:cluster/luneo-prod-eks-primary
    namespace: luneo-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.10.1
    chart: tempo
    helm:
      releaseName: tempo
      values: |
        storage:
          trace:
            backend: s3
            s3:
              bucket: luneo-observability-tempo
              endpoint: s3.eu-west-1.amazonaws.com
              region: eu-west-1
        ingester:
          replicas: 2
        compactor:
          enabled: true
        gateway:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: alb
            hosts:
              - traces.luneo.app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

