apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenylatesttag
spec:
  crd:
    spec:
      names:
        kind: K8sDenyLatestTag
      validation:
        openAPIV3Schema:
          type: object
          properties:
            excludedRegistries:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenylatesttag

        is_excluded_registry(image, registries) {
          some r
          registries[r]
          startswith(image, registries[r])
        }

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          container := input.review.object.spec.containers[_]
          not is_excluded_registry(container.image, {registry | registry := input.parameters.excludedRegistries[_]})
          endswith(lower(container.image), ":latest")
          msg := sprintf("Container image %q uses the forbidden 'latest' tag", [container.image])
        }

