apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: luneo-observability

resources:
  - ../../base
  - applications/kube-prometheus-stack.yaml
  - applications/loki-distributed.yaml
  - applications/tempo.yaml
  - applications/grafana-agent.yaml
  - dashboards/ai-queues-dashboard.yaml
  - dashboards/api-latency-dashboard.yaml
  - alerts/prometheus-rules.yaml
  - secrets/external-secret-grafana.yaml

configMapGenerator:
  - name: observability-settings
    literals:
      - region=eu-west-1
      - prometheusRetention=15d
      - lokiRetention=7d
      - tempoRetention=3d

