# Shopify App Configuration
# Configuration pour l'application Luneo sur Shopify

[application]
name = "Luneo - AI Design Studio"
client_id = "{{SHOPIFY_CLIENT_ID}}"
application_url = "{{SHOPIFY_APP_URL}}"
embedded = true

[access_scopes]
# Scopes nécessaires pour l'intégration Luneo
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers,write_inventory,read_inventory,write_script_tags,read_script_tags,write_themes,read_themes,write_shipping,read_shipping,write_checkouts,read_checkouts,write_reports,read_reports,write_price_rules,read_price_rules,write_marketing_events,read_marketing_events,write_resource_feedbacks,read_resource_feedbacks,write_shopify_payments_payouts,read_shopify_payments_payouts,write_shopify_payments_disputes,read_shopify_payments_disputes,write_translations,read_translations,write_locales,read_locales,write_currency,read_currency,write_publications,read_publications,write_product_listings,read_product_listings,write_inventory_transfers,read_inventory_transfers,write_inventory_levels,read_inventory_levels,write_location,read_location,write_merchant_managed_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_assigned_fulfillment_orders,read_assigned_fulfillment_orders,write_third_party_fulfillment_orders,read_third_party_fulfillment_orders,write_fulfillments,read_fulfillments,write_orders_fulfillments,read_orders_fulfillments,write_orders_transactions,read_orders_transactions,write_orders_payments,read_orders_payments,write_orders_risks,read_orders_risks,write_orders_refunds,read_orders_refunds,write_orders_cancellations,read_orders_cancellations,write_orders_edits,read_orders_edits,write_orders_draft_orders,read_orders_draft_orders,write_orders_cart_transforms,read_orders_cart_transforms,write_orders_checkouts,read_orders_checkouts,write_orders_checkout_tokens,read_orders_checkout_tokens,write_orders_abandoned_checkouts,read_orders_abandoned_checkouts,write_orders_abandoned_checkouts_attributes,read_orders_abandoned_checkouts_attributes,write_orders_abandoned_checkouts_discounts,read_orders_abandoned_checkouts_discounts,write_orders_abandoned_checkouts_line_items,read_orders_abandoned_checkouts_line_items,write_orders_abandoned_checkouts_shipping_address,read_orders_abandoned_checkouts_shipping_address,write_orders_abandoned_checkouts_billing_address,read_orders_abandoned_checkouts_billing_address,write_orders_abandoned_checkouts_shipping_lines,read_orders_abandoned_checkouts_shipping_lines,write_orders_abandoned_checkouts_tax_lines,read_orders_abandoned_checkouts_tax_lines,write_orders_abandoned_checkouts_line_items_taxes,read_orders_abandoned_checkouts_line_items_taxes,write_orders_abandoned_checkouts_discount_codes,read_orders_abandoned_checkouts_discount_codes,write_orders_abandoned_checkouts_attributes,read_orders_abandoned_checkouts_attributes,write_orders_abandoned_checkouts_discounts,read_orders_abandoned_checkouts_discounts,write_orders_abandoned_checkouts_line_items,read_orders_abandoned_checkouts_line_items,write_orders_abandoned_checkouts_shipping_address,read_orders_abandoned_checkouts_shipping_address,write_orders_abandoned_checkouts_billing_address,read_orders_abandoned_checkouts_billing_address,write_orders_abandoned_checkouts_shipping_lines,read_orders_abandoned_checkouts_shipping_lines,write_orders_abandoned_checkouts_tax_lines,read_orders_abandoned_checkouts_tax_lines,write_orders_abandoned_checkouts_line_items_taxes,read_orders_abandoned_checkouts_line_items_taxes,write_orders_abandoned_checkouts_discount_codes,read_orders_abandoned_checkouts_discount_codes"

[auth]
redirect_urls = [
  "{{SHOPIFY_APP_URL}}/auth/callback",
  "{{SHOPIFY_APP_URL}}/auth/install"
]

[webhooks]
api_version = "2023-10"

# Webhooks pour l'intégration Luneo
[[webhooks.subscriptions]]
topic = "app/uninstalled"
uri = "{{SHOPIFY_APP_URL}}/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topic = "orders/create"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/create"

[[webhooks.subscriptions]]
topic = "orders/updated"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/updated"

[[webhooks.subscriptions]]
topic = "orders/paid"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/paid"

[[webhooks.subscriptions]]
topic = "orders/cancelled"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/cancelled"

[[webhooks.subscriptions]]
topic = "orders/fulfilled"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/fulfilled"

[[webhooks.subscriptions]]
topic = "orders/partially_fulfilled"
uri = "{{SHOPIFY_APP_URL}}/webhooks/orders/partially_fulfilled"

[[webhooks.subscriptions]]
topic = "products/create"
uri = "{{SHOPIFY_APP_URL}}/webhooks/products/create"

[[webhooks.subscriptions]]
topic = "products/update"
uri = "{{SHOPIFY_APP_URL}}/webhooks/products/update"

[[webhooks.subscriptions]]
topic = "products/delete"
uri = "{{SHOPIFY_APP_URL}}/webhooks/products/delete"

[[webhooks.subscriptions]]
topic = "customers/create"
uri = "{{SHOPIFY_APP_URL}}/webhooks/customers/create"

[[webhooks.subscriptions]]
topic = "customers/update"
uri = "{{SHOPIFY_APP_URL}}/webhooks/customers/update"

[[webhooks.subscriptions]]
topic = "customers/delete"
uri = "{{SHOPIFY_APP_URL}}/webhooks/customers/delete"

[[webhooks.subscriptions]]
topic = "inventory_levels/update"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_levels/update"

[[webhooks.subscriptions]]
topic = "inventory_levels/connect"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_levels/connect"

[[webhooks.subscriptions]]
topic = "inventory_levels/disconnect"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_levels/disconnect"

[[webhooks.subscriptions]]
topic = "inventory_items/create"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_items/create"

[[webhooks.subscriptions]]
topic = "inventory_items/update"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_items/update"

[[webhooks.subscriptions]]
topic = "inventory_items/delete"
uri = "{{SHOPIFY_APP_URL}}/webhooks/inventory_items/delete"

[[webhooks.subscriptions]]
topic = "locations/create"
uri = "{{SHOPIFY_APP_URL}}/webhooks/locations/create"

[[webhooks.subscriptions]]
topic = "locations/update"
uri = "{{SHOPIFY_APP_URL}}/webhooks/locations/update"

[[webhooks.subscriptions]]
topic = "locations/delete"
uri = "{{SHOPIFY_APP_URL}}/webhooks/locations/delete"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "{{SHOPIFY_DEV_STORE_URL}}"
include_config_on_deploy = true

[deployment]
environments = ["production", "staging", "development"]



